name: CICD for Group 2 Chat Application
run-name: ${{ github.actor }} is running CICD for Group 2 Chat Application


on:
  workflow_dispatch:
    inputs:
      access_url:
        description: 'Access URL'
        required: true
        default: ''
  
# Define permissions for this workflow, which can be added at either the job or workflow level.      
permissions:
  id-token: write # This is required for requesting the JWT
  actions: read
  contents: read
  security-events: write


jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The jobs are triggered by a ${{ github.event_name }} event on ${{ github.event.pull_request.head.ref }} branch."

  show-access-url:
    runs-on: ubuntu-latest
    needs: pre-deploy
    steps:
      - name: Show the access URL
        id: access_url
        run: |
          echo "access_url=${{ github.event.inputs.access_url }}"
          echo "${{ github.event.inputs.access_url }}" >> $GITHUB_OUTPUT

  test-access-url:
    runs-on: ubuntu-latest
    needs: show-access-url
    steps:
      - name: Show the access URL
        run: |
          access_url=${{ needs.show-access-url.outputs.access_url }}
          echo "access_url=${{ needs.show-access-url.outputs.access_url }}"
          echo "access_url=$access_url"
  
# Add DAST scan

      



  # Define the "get-aws-info" job, which uses a reusable workflow defined in another file. 
  get-aws-info:
    uses: ./.github/workflows/get-aws-info.yml